
package com.ttk.business.webservice.haad;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Webservices", targetNamespace = "https://www.shafafiya.org/v2/", wsdlLocation = "file:/home/tipsint/jboss-as-7.1.3.Final/bin/haad-wsdl/haadv2wsdl.wsdl")
public class Webservices
    extends Service
{

    private final static URL WEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICES_EXCEPTION;
    private final static QName WEBSERVICES_QNAME = new QName("https://www.shafafiya.org/v2/", "Webservices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/tipsint/jboss-as-7.1.3.Final/bin/haad-wsdl/haadv2wsdl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICES_WSDL_LOCATION = url;
        WEBSERVICES_EXCEPTION = e;
    }

    public Webservices() {
        super(__getWsdlLocation(), WEBSERVICES_QNAME);
    }

    public Webservices(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICES_QNAME, features);
    }

    public Webservices(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICES_QNAME);
    }

    public Webservices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICES_QNAME, features);
    }

    public Webservices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Webservices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebservicesSoap
     */
    @WebEndpoint(name = "WebservicesSoap")
    public WebservicesSoap getWebservicesSoap() {
        return super.getPort(new QName("https://www.shafafiya.org/v2/", "WebservicesSoap"), WebservicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebservicesSoap
     */
    @WebEndpoint(name = "WebservicesSoap")
    public WebservicesSoap getWebservicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.shafafiya.org/v2/", "WebservicesSoap"), WebservicesSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WebservicesSoap
     */
    @WebEndpoint(name = "WebservicesSoap12")
    public WebservicesSoap getWebservicesSoap12() {
        return super.getPort(new QName("https://www.shafafiya.org/v2/", "WebservicesSoap12"), WebservicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebservicesSoap
     */
    @WebEndpoint(name = "WebservicesSoap12")
    public WebservicesSoap getWebservicesSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.shafafiya.org/v2/", "WebservicesSoap12"), WebservicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICES_EXCEPTION!= null) {
            throw WEBSERVICES_EXCEPTION;
        }
        return WEBSERVICES_WSDL_LOCATION;
    }

}
