
package com.ttk.business.webservice.dhponewmember;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMemberRegistration", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMemberRegistration {


    /**
     * 
     * @param pwd
     * @param login
     * @param fileContent
     * @return
     *     returns com.ttk.business.webservice.dhponewmember.UploadResponse
     */
    @WebMethod(operationName = "UploadMemberRegister", action = "http://tempuri.org/IMemberRegistration/UploadMemberRegister")
    @WebResult(name = "UploadMemberRegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadMemberRegister", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.UploadMemberRegister")
    @ResponseWrapper(localName = "UploadMemberRegisterResponse", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.UploadMemberRegisterResponse")
    public UploadResponse uploadMemberRegister(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "fileContent", targetNamespace = "http://tempuri.org/")
        byte[] fileContent);

    /**
     * 
     * @param pwd
     * @param login
     * @param searchType
     * @param searchValue
     * @return
     *     returns com.ttk.business.webservice.dhponewmember.MemberInsuranceResponse
     */
    @WebMethod(operationName = "GetMemberPolices", action = "http://tempuri.org/IMemberRegistration/GetMemberPolices")
    @WebResult(name = "GetMemberPolicesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMemberPolices", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.GetMemberPolices")
    @ResponseWrapper(localName = "GetMemberPolicesResponse", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.GetMemberPolicesResponse")
    public MemberInsuranceResponse getMemberPolices(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "searchType", targetNamespace = "http://tempuri.org/")
        Integer searchType,
        @WebParam(name = "searchValue", targetNamespace = "http://tempuri.org/")
        String searchValue);

    /**
     * 
     * @param dateOfBirth
     * @param pwd
     * @param nationality
     * @param gender
     * @param fileNo
     * @param login
     * @return
     *     returns com.ttk.business.webservice.dhponewmember.ValidateMemberFileNoResponse
     */
    @WebMethod(operationName = "ValidateMember", action = "http://tempuri.org/IMemberRegistration/ValidateMember")
    @WebResult(name = "ValidateMemberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateMember", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.ValidateMember")
    @ResponseWrapper(localName = "ValidateMemberResponse", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.ValidateMemberResponse")
    public ValidateMemberFileNoResponse validateMember(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "fileNo", targetNamespace = "http://tempuri.org/")
        String fileNo,
        @WebParam(name = "gender", targetNamespace = "http://tempuri.org/")
        Integer gender,
        @WebParam(name = "dateOfBirth", targetNamespace = "http://tempuri.org/")
        String dateOfBirth,
        @WebParam(name = "nationality", targetNamespace = "http://tempuri.org/")
        String nationality);

    /**
     * 
     * @param tpaLicense
     * @param policySequeance
     * @param pwd
     * @param nationality
     * @param memberType
     * @param gender
     * @param dateofbirth
     * @param login
     * @param payerLicense
     * @param referenceID
     * @return
     *     returns com.ttk.business.webservice.dhponewmember.GenerateMamberResponse
     */
    @WebMethod(operationName = "GenerateMemberID", action = "http://tempuri.org/IMemberRegistration/GenerateMemberID")
    @WebResult(name = "GenerateMemberIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerateMemberID", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.GenerateMemberID")
    @ResponseWrapper(localName = "GenerateMemberIDResponse", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.GenerateMemberIDResponse")
    public GenerateMamberResponse generateMemberID(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "dateofbirth", targetNamespace = "http://tempuri.org/")
        String dateofbirth,
        @WebParam(name = "gender", targetNamespace = "http://tempuri.org/")
        Integer gender,
        @WebParam(name = "nationality", targetNamespace = "http://tempuri.org/")
        Integer nationality,
        @WebParam(name = "memberType", targetNamespace = "http://tempuri.org/")
        Integer memberType,
        @WebParam(name = "referenceID", targetNamespace = "http://tempuri.org/")
        String referenceID,
        @WebParam(name = "payerLicense", targetNamespace = "http://tempuri.org/")
        String payerLicense,
        @WebParam(name = "TPALicense", targetNamespace = "http://tempuri.org/")
        String tpaLicense,
        @WebParam(name = "policySequeance", targetNamespace = "http://tempuri.org/")
        String policySequeance);

    /**
     * 
     * @param pwd
     * @param transactionId
     * @param login
     * @return
     *     returns com.ttk.business.webservice.dhponewmember.TransactionResponse
     */
    @WebMethod(operationName = "DownloadMemberTransaction", action = "http://tempuri.org/IMemberRegistration/DownloadMemberTransaction")
    @WebResult(name = "DownloadMemberTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DownloadMemberTransaction", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.DownloadMemberTransaction")
    @ResponseWrapper(localName = "DownloadMemberTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.DownloadMemberTransactionResponse")
    public TransactionResponse downloadMemberTransaction(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "transactionId", targetNamespace = "http://tempuri.org/")
        String transactionId);

    /**
     * 
     * @param pwd
     * @param fromDate
     * @param memberId
     * @param login
     * @param toDate
     * @return
     *     returns com.ttk.business.webservice.dhponewmember.TransactionSearchResponse
     */
    @WebMethod(operationName = "SearchTransaction", action = "http://tempuri.org/IMemberRegistration/SearchTransaction")
    @WebResult(name = "SearchTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchTransaction", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.SearchTransaction")
    @ResponseWrapper(localName = "SearchTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.SearchTransactionResponse")
    public TransactionSearchResponse searchTransaction(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate,
        @WebParam(name = "memberId", targetNamespace = "http://tempuri.org/")
        String memberId);

    /**
     * 
     * @param pwd
     * @param login
     * @param fileContent
     * @return
     *     returns com.ttk.business.webservice.dhponewmember.UploadResponse
     */
    @WebMethod(operationName = "UpdateMember", action = "http://tempuri.org/IMemberRegistration/UpdateMember")
    @WebResult(name = "UpdateMemberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateMember", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.UpdateMember")
    @ResponseWrapper(localName = "UpdateMemberResponse", targetNamespace = "http://tempuri.org/", className = "com.ttk.business.webservice.dhponewmember.UpdateMemberResponse")
    public UploadResponse updateMember(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "fileContent", targetNamespace = "http://tempuri.org/")
        byte[] fileContent);

}
