
package com.ttk.business.webservice.dhponewmember;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MemberRegistration", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://mr.eclaimlink.ae/v2/MemberRegistration.svc?wsdl")
public class MemberRegistration
    extends Service
{

    private final static URL MEMBERREGISTRATION_WSDL_LOCATION;
    private final static WebServiceException MEMBERREGISTRATION_EXCEPTION;
    private final static QName MEMBERREGISTRATION_QNAME = new QName("http://tempuri.org/", "MemberRegistration");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://mr.eclaimlink.ae/v2/MemberRegistration.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBERREGISTRATION_WSDL_LOCATION = url;
        MEMBERREGISTRATION_EXCEPTION = e;
    }

    public MemberRegistration() {
        super(__getWsdlLocation(), MEMBERREGISTRATION_QNAME);
    }

    public MemberRegistration(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBERREGISTRATION_QNAME, features);
    }

    public MemberRegistration(URL wsdlLocation) {
        super(wsdlLocation, MEMBERREGISTRATION_QNAME);
    }

    public MemberRegistration(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBERREGISTRATION_QNAME, features);
    }

    public MemberRegistration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberRegistration(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMemberRegistration
     */
    @WebEndpoint(name = "basicEndpoint")
    public IMemberRegistration getBasicEndpoint() {
        return super.getPort(new QName("http://tempuri.org/", "basicEndpoint"), IMemberRegistration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMemberRegistration
     */
    @WebEndpoint(name = "basicEndpoint")
    public IMemberRegistration getBasicEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "basicEndpoint"), IMemberRegistration.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBERREGISTRATION_EXCEPTION!= null) {
            throw MEMBERREGISTRATION_EXCEPTION;
        }
        return MEMBERREGISTRATION_WSDL_LOCATION;
    }

}
